services:
  mysql:
    image: mysql:latest
    environment:
    - MYSQL_DATABASE=warehouse
    - MYSQL_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
    - 3307:3306

  clustered-data-warehouse:
    image: clustered-data-warehouse:latest
    container_name: clustered-data-warehouse
    build:
      context: /
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/warehouse?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./ClusteredDataWarehouse:/app  # Mount your project directory inside the container
    command: []
